### ISSUE TITLE
Sounds are cut off at the beginning

### ISSUE THREAD

**Issue by Niektory** [fifengine/fifengine#1018]
The effect is more noticeable when framerate is low. It seems the time that passes between [this](https://github.com/fifengine/fifengine/blob/ec059ef2c48b346e404d0f8c0a83798e1da707a2/engine/core/audio/soundemitter.cpp#L346) and [this](https://github.com/fifengine/fifengine/blob/ec059ef2c48b346e404d0f8c0a83798e1da707a2/engine/core/audio/soundemitter.cpp#L739) is the time that is cut off. If I set `timediff = 0;` the whole sound is played correctly.

**Comment by Niektory** [comment]
Works fine now, except when the sound is really short (shorter than the time between play and the first update) it won't play.

**Comment by helios2000** [comment]
Ok I'll fix the end detection too. But the idea behind it, is to handle sound sources that go out of range or come into range. If your FPS is extremly low and your track is extremly short it will simply be skippted.
The same will happen if you have tracks that startet but no source handler is there. I do prefer the way to use timestamps instead of starting the sound maybe 5 minutes after play was called.

**Comment by Niektory** [comment]
Well, the first problem was very noticeable with my GUI clicking sound at 60 FPS (so not extremely low). I did set it lower afterwards for testing so I noticed the second problem. Running out of source handlers or being out of range is another story, I agree that playing the sound much later wouldn't be right.

**Comment by helios2000** [comment]
That was only to explain why there are timestamps around and there can exists situations where clips are skipped. You are right that it should work on low FPS too and I hope it is fixed now, even for short tracks. I'm still amazed that you hear a difference of 16ms.
