### ISSUE TITLE
Window width settings are not fully respected when using two screens

### ISSUE THREAD

**Issue by nihathrael** [fifengine/fifengine#1048]
When I launch Unknown Horizons or the pychan demo in windowed mode, with the resolution specified to `1440x900` in the `settings.xml`, the resulting window will actually be `1600x900` pixels, as measured with `xwininfo`. In Unknown Horizons this leads to all sorts of artifacts while in game. 

Environment:
- Arch Linux
- 2 1920x1080 Resolution Screens (1 laptop built-in and 1 external)
- Running xorg server with KDE Plasma.

This behavior does not appear when I disable my integrated screen and only start the games on the external monitor. So for some reason the app is gaining an additional 140 pixels for the second screen?

**Comment by helios2000** [comment]
That is not really a bug. If the driver / SDL is not able to create a window with the specified resolution it will use the next available resolution.

**Comment by helios2000** [comment]
Have tested it, here it works without problems. I think the problem is really that SDL was not able to create a windows with the specified size.
So on client side it is always better to check the available ScreenModes (engine.getDeviceCaps().getSupportedScreenModes()).
The other way would be that Fife simply throws an error if a resolution is not possible.
