### ISSUE TITLE
cegui download broken on appveyor

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#1070]
.$env:APPVEYOR_BUILD_FOLDER\build\appveyor\dl_extract_cegui-sdk.ps1
Invoke-RestMethod : Could not find a part of the path 'C:\projects\fifengine-dependencies\downloads\'.
At C:\projects\fifengine\build\appveyor\dl_extract_cegui-sdk.ps1:34 char:1
+ Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifact ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by LinuxDonald** [comment]
@Beliaar @jakoch any ideas?

**Comment by Beliaar** [comment]
@LinuxDonald It seems the folder  'C:\projects\fifengine-dependencies\downloads' does not exist, for whatever reason. Just creating it before that line should probably fix the problem.

**Comment by jakoch** [comment]
Happy new year everyone! 

I think the problem is that the downloads on Appveyor are not persistent. 
Build artifacts older than 6 months are permanently removed from AppVeyor artifact storage, see
https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

The second problem is that the cegui guys do not release in a CI way. 
They are on [bitbucket](https://bitbucket.org/cegui/cegui/src), but i couldn't find any repository with build artifacts could fetch.
To circumvent this problem i've upload the latest cegui release to our last Github Release v0.4.1,
https://github.com/fifengine/fifengine/releases/download/0.4.1/cegui-sdk-VC14-x86.zip

I've worked a cmake-get-cegui script (using that URL) some days before christmas, see the last few 
changes in the [cmake-get-cegui](https://github.com/fifengine/fifengine/tree/cmake-get-cegui) branch.

**Comment by MarkusHackspacher** [comment]
If not possible to disable CEGUI in windows, too.
Linux had not CEGUI support, half year ago.

https://github.com/fifengine/fifengine/commit/fa6ea6d229f28fd9bd2718507601dc50bddfb702

**Comment by jakoch** [comment]
Thanks for reporting that issue, Markus. 
The question is: What is our cegui default value ON or OFF?
I think it's CEGUI off by default, because then the GUI defaults to fifechan = ON, right?
