### ISSUE TITLE
How to handle the window close button being pressed?

### ISSUE THREAD

**Issue by thorsummoner** [fifengine/fifengine#869]
Specifically in the python scripting context, none of the tutorials handle pressing the window close button. That is the close button in the window decorator.

**Comment by stubb** [comment]
Just read your question. Since fifengine uses SDL for the window handling, you simply can poll for the SDL_QUIT event which is sent when the close button of the window was pressed.
Here is a small example
``` c++
#include <SDL2/SDL.h>
#include <iostream>

int main(int argc, char **argv)
{
    SDL_Window *window = NULL;
    SDL_Event events;
    SDL_Init(SDL_INIT_EVERYTHING);
    window = SDL_CreateWindow("Handle SDL_QUIT Event", 0, 0, 640, 480, 0);
    bool running = true;
    while (running)
    {
        std::cout << "Running" << std::endl;
        while (SDL_PollEvent(&events))
        {
            if (events.type == SDL_QUIT)
            {
                std::cout << "Close event triggered" << std::endl;
                running = false;
            }
        }
        SDL_Delay(1000);
    }
    SDL_DestroyWindow(window);
    SDL_Quit();
}
```
Compiled with:
``` bash
g++ handleSdlQuit.cpp -I/usr/include/SDL2 -lSDL2  -o demo.out
```

**Comment by prock-fife** [comment]
I believe what you are looking for is the fife.CMD_QUIT_GAME (see example in the shooter demo in the ApplicationListener).  SDL_WINDOWEVENT_CLOSE gets translated to CMD_QUIT_GAME here: https://github.com/fifengine/fifengine/blob/master/engine/core/eventchannel/eventmanager.cpp#L537

**Comment by prock-fife** [comment]
Thinking about it more it may be beneficial to have a specific command so you know the window manager asked FIFE to close (user pressed X or alt-f4... etc etc).  In python code you have no way to determine why the CMD_QUIT_GAME event got created because even the game itself can raise that event.  Looking at the naming conventions of these commands we should look at standardizing window commands.  Something like:

CMD_QUIT_GAME -> CMD_WDW_QUIT
CMD_MOUSE_FOCUS_GAINED -> CMD_WDW_MOUSE_GAINED
CMD_MOUSE_FOCUS_LOST -> CMD_WDW_MOUSE_LOST
CMD_INPUT_FOCUS_GAINED -> CMD_WDW_INPUT_GAINED
CMD_INPUT_FOCUS_LOST -> CMD_WDW_INPUT_LOST
CMD_APP_RESTORED -> CMD_WDW_RESTORED
CMD_APP_ICONIFIED -> CMD_WDW_ICONIFIED

**Comment by prock-fife** [comment]
Closing... please re-open if I didn't answer your question.

**Comment by thorsummoner** [comment]
Would be great if the code examples could be extended to include handling
exits correctly.

**Comment by prock-fife** [comment]
The all demos should handle exits just fine.   Maybe I'm misunderstanding the issue??  The window manager should be sending a SDL_WINDOWEVENT_CLOSE event which gets translated to CMD_QUIT_GAME by FIFE.

**Comment by thorsummoner** [comment]
My memory has faded, but IIRC the examples I was working with did nothing
when the window decorator exit button was pressed.

**Comment by stubb** [comment]
Some official examples or something self written? Feel free to show the code, so we can help to figure out the issue.
