### ISSUE TITLE
Appveyor Deploy problem

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#944]
I found this:

http://help.appveyor.com/discussions/problems/2168-cant-create-a-github-release

**Comment by LinuxDonald** [comment]
@jakoch maybe you know if that could help?

**Comment by jakoch** [comment]
- No, that won't help, because that's not the issue.
- These artifacts are deployed: https://github.com/fifengine/fifengine/blob/master/appveyor.yml#L158
  - add `LibfifeReleaseArtifact`, which is missing
- uncomment the artifact section: https://github.com/fifengine/fifengine/blob/master/appveyor.yml#L144-L150
  - adjust the path entries, so that they match the files created in the `after_build` section
    - you find the files on the lines with `appveyor PushArtifact`
