### ISSUE TITLE
python bindings probably should not install cegui/librocket/etc. unconditionally

### ISSUE THREAD

**Issue by ignatenkobrain** [fifengine/fifengine#987]
If option cegui/librocket/etc. is set to OFF, we probably should not install such files for python.

Although I'm not entirely sure what's the idea behind.

**Comment by jakoch** [comment]
Thank you for reporting the issue.

Do you mean the py files inside `engine/python/fife/extensions/{cegui|fifechan|librocket}` folder?https://github.com/fifengine/fifengine/tree/master/engine/python/fife/extensions

Otherwise, please give me a link to the log of one of the CI services, 
so that i see which unconditionally installed artifact(s) you mean.

Thanks, Jens

**Comment by helios2000** [comment]
@jakoch Is this fixed?

**Comment by LinuxDonald** [comment]
I have already merged his work.

**Comment by helios2000** [comment]
Well, then we can close it or not?

**Comment by LinuxDonald** [comment]
I close it. For me it looks like its fixed.
